apiVersion: microservices.application.io/v1alpha1
kind: MicroserviceConfig
spec:
  services:
    - name: convey
      binaryPath: /home/lzuccarelli/Projects/convey/target/release
      registry: localhost:5000/test/convey:v0.1.0
      version: 0.1.1
      authors: 
        - lmzuccarelli luzuccar@redhat.com
        - mtroisi hello@marcotroisi.com
      description: "Simple demo of a microservice binary to signed package"
      env:
        - name: LOG_LEVEL
          value: TRACE
      args:
        - name: "--config"
          value: "lb-setup.toml"
    - name: hypertls-microservice
      binaryPath: /home/lzuccarelli/Projects/rust-hypertls-microservice/target/release
      registry: localhost:5000/test/hyepertls-microservice:v0.1.0
      version: 0.1.1
      authors: 
        - lmzuccarelli luzuccar@redhat.com
        - mtroisi hello@marcotroisi.com
      description: "Simple demo of a microservice binary to signed package"

